support upgrade snapshot version

diff --git a/env b/env
--- a/env
+++ b/env
@@ -1,3 +1,35 @@
 
-OPENWRT_REPO=downloads.openwrt.org
-OPENWRT_VERSION=19.07.6
+export OPENWRT_REPO=downloads.openwrt.org
+export OPENWRT_VERSION=19.07.6
+
+prepare_env()
+{
+	local _dir=$1
+
+	# source OPENWRT_BOARD
+	. /etc/os-release
+	export OPENWRT_BOARD
+
+	OPENWRT_MODEL=$(sed -n 's/.*"id":\s"\([^"]\+\)",.*/\1/p' /etc/board.json|tr ',' '_')
+	if [ -z "$OPENWRT_MODEL" ];then
+		echo "ERROR: Can not detect device model via /etc/board.json"
+		exit 1
+	fi
+
+	for envfile in models/${OPENWRT_MODEL}/env .local_env ; do
+		if [ -e "${_dir}/${envfile}" ];then
+			. "${_dir}/${envfile}"
+		fi
+	done
+
+	if [ "$VERSION_ID" = "snapshot" ];then
+		export OPENWRT_IS_SNAPSHOT=true
+		export OPENWRT_MIRROR=${OPENWRT_SNAPSHOT_MIRROR:-$OPENWRT_MIRROR}
+		export OPENWRT_URL=https://${OPENWRT_MIRROR:-$OPENWRT_REPO}/snapshot/targets/${OPENWRT_BOARD}
+		export OPENWRT_SYSUPGRADE_FILE=openwrt-$(echo ${OPENWRT_BOARD}|tr '/' '-')-${OPENWRT_MODEL}-squashfs-sysupgrade.bin
+	else
+		export OPENWRT_IS_SNAPSHOT=false
+		export OPENWRT_URL=https://${OPENWRT_MIRROR:-$OPENWRT_REPO}/releases/${OPENWRT_VERSION}/targets/${OPENWRT_BOARD}
+		export OPENWRT_SYSUPGRADE_FILE=openwrt-${OPENWRT_VERSION}-$(echo ${OPENWRT_BOARD}|tr '/' '-')-${OPENWRT_MODEL}-squashfs-sysupgrade.bin
+	fi
+}
